name = "searches-do"
route = { pattern = "*/*", zone_name = "searches.do" }
usage_model = "unbound"
main = "dist/index.mjs"
compatibility_date = "2022-08-25"

kv_namespaces = [
	{ binding = "DOCUMENT_STORE", id = "c19828a92fb742b780a7f11fbec15270" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"

services = [
]

[durable_objects]
bindings = [ { name = "TextSearchDO", class_name = "TextSearchDO"} ]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["TextSearchDO"]

[miniflare]
durable_objects_persist = "./data/"  
kv_persist = "./data/"