name = "searches-do"
route = { pattern = "*/*", zone_name = "searches.do" }
worker_dev = false
usage_model = "unbound"
account_id = "2dcc5a4f486a50625b4167e90d113158"
main = "dist/index.mjs"
compatibility_date = "2022-08-25"

kv_namespaces = [
	{ binding = "DOCUMENT_STORE", id = "9e05323a3c3c44f189736a3107818e7f" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"

services = [
]

[durable_objects]
bindings = [ { name = "TextSearchDO", class_name = "TextSearchDO"} ]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["TextSearchDO"]

[miniflare]
durable_objects_persist = "./data/"  
kv_persist = "./data/"